Repository Activiti/activiti-cloud-audit-service, pull requests merged in 2018-12, with the labels that each got.

#99 fix(versions): update Activiti/activiti-cloud-audit-service versions
  pom.xml
Labels: in progress, updatebot

#100 fix(versions): update Activiti/activiti-cloud-audit-service versions
  pom.xml
Labels: in progress, updatebot

#92 feat: ProcessUpdatedAuditEventEntity implemented to support update process command
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/converters/ProcessUpdatedEventConverter.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/ProcessUpdatedAuditEventEntity.java
  activiti-cloud-starter-audit/src/test/java/org/activiti/cloud/starter/audit/tests/it/AuditServiceIT.java
Labels: in progress

#101 Handle task update
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/converters/TaskUpdatedEventConverter.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/TaskUpdatedEventEntity.java
  activiti-cloud-starter-audit/src/test/java/org/activiti/cloud/starter/audit/tests/it/AuditServiceIT.java
Labels: in progress

#104 fix(versions): update Activiti/activiti-cloud-audit-service versions
  pom.xml
Labels: in progress, updatebot

#102 Set entity for process updated and process suspended events
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/converters/ProcessSuspendedEventConverter.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/converters/ProcessUpdatedEventConverter.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/BPMNActivityAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/ProcessAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/TaskAuditEventEntity.java
  activiti-cloud-starter-audit/src/test/java/org/activiti/cloud/starter/audit/tests/it/AuditServiceIT.java
Labels: in progress

#105 fix(versions): update Activiti/activiti-cloud-audit-service versions
  pom.xml
Labels: updatebot

#107 fix(versions): update Activiti/activiti-cloud-audit-service versions
  pom.xml
Labels: updatebot

#108 fix(versions): update Activiti/activiti-cloud-audit-service versions
  pom.xml
Labels: updatebot

#110 fix(versions): update Activiti/activiti-cloud-audit-service versions
  pom.xml
Labels: updatebot

#111 fix(versions): update Activiti/activiti-cloud-audit-service versions
  pom.xml
Labels: updatebot
