Repository Activiti/activiti-cloud-audit-service, pull requests merged in 2018-11, with the labels that each got.

#79 update org.activiti.cloud.common:activiti-cloud-service-common-dependencies to 7.0.39
  pom.xml
Labels: updatebot

#80 update org.activiti.cloud.common:activiti-cloud-service-common-dependencies to 7.0.40
  pom.xml
Labels: updatebot

#81 update org.activiti.cloud.common:activiti-cloud-service-common-dependencies to 7.0.41
  pom.xml
Labels: updatebot

#82 fix: Filtering by instance id and event type in audit
  activiti-cloud-starter-audit/src/test/java/org/activiti/cloud/starter/audit/tests/it/AuditServiceIT.java
Labels: in progress

#83 update org.activiti.cloud.build:activiti-cloud-parent to 7.0.35
  pom.xml
Labels: in progress, updatebot

#85 update org.activiti.cloud.common:activiti-cloud-service-common-dependencies to 7.0.42
  pom.xml
Labels: in progress, updatebot

#86 update org.activiti.cloud.common:activiti-cloud-service-common-dependencies to 7.0.46
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/converters/json/JpaJsonConverter.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/converters/json/SequenceFlowJpaJsonConverter.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/SequenceFlowAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/test/java/org/activiti/cloud/services/audit/jpa/controller/AuditEventsControllerImplIT.java
  activiti-cloud-services-audit-jpa/src/test/java/org/activiti/cloud/services/audit/jpa/converters/BPMNActivityJpaJsonConverterTest.java
  activiti-cloud-services-audit-jpa/src/test/java/org/activiti/cloud/services/audit/jpa/converters/SequenceFlowJpaJsonConverterTest.java
  activiti-cloud-starter-audit/src/test/resources/application.properties
  pom.xml
Labels: in progress, updatebot

#88 update org.activiti.cloud.common:activiti-cloud-service-common-dependencies to 7.0.47
  pom.xml
Labels: in progress, updatebot

#84 Configure Updatebot single PR for cloud-dependencies tests and automatic merge with Mergify
  .mergify.yml
  .updatebot.yml
Labels: enhancement, in progress

#87 update org.activiti.cloud.build:activiti-cloud-parent to 7.0.36
  pom.xml
Labels: in progress, updatebot

#89 update org.activiti.cloud.common:activiti-cloud-service-common-dependencies to 7.0.49
  pom.xml
Labels: in progress, updatebot

#90 Add activiti-cloud-audit-dependencies-tests module
  .mergify.yml
  activiti-cloud-audit-dependencies/pom.xml
  activiti-cloud-services-audit-api/pom.xml
  activiti-cloud-services-audit-jpa/pom.xml
  activiti-cloud-starter-audit/pom.xml
  dependencies-tests/pom.xml
  pom.xml
Labels: enhancement, in progress

#91 fix(versions): update Activiti/activiti-cloud-audit-service versions
  pom.xml
Labels: in progress, updatebot

#93 fix(versions): update Activiti/activiti-cloud-audit-service versions
  pom.xml
Labels: in progress, updatebot

#95 fix(versions): update Activiti/activiti-cloud-audit-service versions
  pom.xml
Labels: in progress, updatebot

#94 remove bean overriding
  activiti-cloud-starter-audit/src/test/resources/application.properties
Labels: in progress

#97 fix(versions): update Activiti/activiti-cloud-audit-service versions
  pom.xml
Labels: in progress, updatebot

#98 fix(versions): update Activiti/activiti-cloud-audit-service versions
  pom.xml
Labels: in progress, updatebot
