Repository Activiti/activiti-cloud-audit-service, pull requests merged in 2019-09, with the labels that each got.

#211 fix(versions): update Activiti/activiti-cloud-audit-service versions into develop
  pom.xml
Labels: updatebot

#212 fix(versions): update Activiti/activiti-cloud-audit-service versions into develop
  pom.xml
Labels: updatebot

#213 fix(versions): update Activiti/activiti-cloud-audit-service versions into develop
  pom.xml
Labels: updatebot

#214 fix(versions): update Activiti/activiti-cloud-audit-service versions into develop
  pom.xml
Labels: updatebot

#215 fix(versions): update Activiti/activiti-cloud-audit-service versions into develop
  pom.xml
Labels: updatebot

#219 fix(versions): update Activiti/activiti-cloud-audit-service versions into develop
  pom.xml
Labels: updatebot

#218 feat: Add support for BPMN Message Audit events
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/conf/AuditJPAAutoConfiguration.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/converters/MessageReceivedEventConverter.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/converters/MessageSentEventConverter.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/converters/MessageWaitingEventConverter.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/converters/json/MessageJpaJsonConverter.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/MessageAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/MessageReceivedAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/MessageSentAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/MessageWaitingAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/test/java/org/activiti/cloud/services/audit/jpa/controller/AuditEventsControllerImplIT.java
  activiti-cloud-services-audit-jpa/src/test/java/org/activiti/cloud/services/audit/jpa/converters/MessageEventConverterTest.java
Labels: enhancement

#220 fix(versions): update Activiti/activiti-cloud-audit-service versions into develop
  pom.xml
Labels: updatebot

#222 fix: add missing BPMNMessage Jackson mapping configuration
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/converters/json/JpaJsonConverter.java
Labels: bug

#225 fix(versions): update Activiti/activiti-cloud-audit-service versions into develop
  pom.xml
Labels: updatebot

#226 fix(versions): update Activiti/activiti-cloud-audit-service versions into develop
  pom.xml
Labels: updatebot

#223 fix: Remove @Lob annotation with TEXT column definition
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/ActivityCancelledAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/ActivityCompletedAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/ActivityStartedAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/AuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/BPMNActivityAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/IntegrationEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/IntegrationRequestSentEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/IntegrationResultReceivedEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/MessageAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/MessageReceivedAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/MessageSentAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/MessageWaitingAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/ProcessAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/ProcessCancelledAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/ProcessCompletedEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/ProcessCreatedAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/ProcessDeployedAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/ProcessResumedAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/ProcessStartedAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/ProcessSuspendedAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/ProcessUpdatedAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/SequenceFlowAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/SignalReceivedAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/TaskAssignedEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/TaskAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/TaskCancelledEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/TaskCandidateGroupAddedEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/TaskCandidateGroupRemovedEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/TaskCandidateUserAddedEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/TaskCandidateUserRemovedEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/TaskCompletedEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/TaskCreatedEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/TaskSuspendedEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/TaskUpdatedEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/TimerAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/TimerCancelledAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/TimerExecutedAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/TimerFailedAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/TimerFiredAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/TimerRetriesDecrementedAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/TimerScheduledAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/VariableAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/VariableCreatedEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/VariableDeletedEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/VariableUpdatedEventEntity.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/repository/EventsRepository.java
Labels: bug

#227 fix(versions): update Activiti/activiti-cloud-audit-service versions into develop
  pom.xml
Labels: updatebot
