Repository Activiti/activiti-cloud-audit-service, pull requests merged in 2019-11, with the labels that each got.

#244 fix(versions): update Activiti/activiti-cloud-audit-service versions into develop
  pom.xml
Labels: updatebot

#245 fix(versions): update Activiti/activiti-cloud-audit-service versions into develop
  pom.xml
Labels: updatebot

#246 fix(versions): update Activiti/activiti-cloud-audit-service versions into develop
  pom.xml
Labels: updatebot

#247 fix(versions): update Activiti/activiti-cloud-audit-service versions into develop
  pom.xml
Labels: updatebot

#249 fix(versions): update Activiti/activiti-cloud-audit-service versions into develop
  pom.xml
Labels: updatebot

#248 AAE-102 implementation of MessageSubscriptionCancelledAuditEventEntity
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/conf/AuditJPAAutoConfiguration.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/converters/MessageSubscriptionCancelledEventConverter.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/converters/json/JpaJsonConverter.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/converters/json/MessageSubscriptionJpaJsonConverter.java
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/events/MessageSubscriptionCancelledAuditEventEntity.java
  activiti-cloud-services-audit-jpa/src/test/java/org/activiti/cloud/services/audit/jpa/converters/MessageSubscriptionCancelledEventConverterTest.java
  activiti-cloud-starter-audit/src/main/resources/config/audit/liquibase/changelog/03-alter.pg.schema.m5.sql
  activiti-cloud-starter-audit/src/main/resources/config/audit/liquibase/changelog/h2.schema.sql
  activiti-cloud-starter-audit/src/main/resources/config/audit/liquibase/master.xml
  activiti-cloud-starter-audit/src/test/java/org/activiti/cloud/starter/audit/tests/it/AuditServiceIT.java
Labels: enhancement, ready-for-review

#250 fix(versions): update Activiti/activiti-cloud-audit-service versions into develop
  pom.xml
Labels: updatebot

#251 fix(versions): update Activiti/activiti-cloud-audit-service versions into develop
  pom.xml
Labels: updatebot

#252 fix(versions): update Activiti/activiti-cloud-audit-service versions into develop
  pom.xml
Labels: updatebot

#253 fix(versions): update Activiti/activiti-cloud-audit-service versions into develop
  pom.xml
Labels: updatebot

#254 fix(versions): update Activiti/activiti-cloud-audit-service versions into develop
  pom.xml
Labels: updatebot

#255 fix(versions): update Activiti/activiti-cloud-audit-service versions into develop
  pom.xml
Labels: updatebot

#256 fix(versions): update Activiti/activiti-cloud-audit-service versions into develop
  activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/converters/SequenceFlowTakenEventConverter.java
  pom.xml
Labels: updatebot

#257 fix(versions): update Activiti/activiti-cloud-audit-service versions into develop
  pom.xml
Labels: updatebot

#190 AAE-771 Tests extended to check taskDefinitionKey
  activiti-cloud-services-audit-jpa/src/test/java/org/activiti/cloud/services/audit/jpa/converters/TaskCreatedEventConverterTest.java
  activiti-cloud-starter-audit/src/test/java/org/activiti/cloud/starter/audit/tests/it/AuditServiceIT.java
Labels: ready-for-review

#240 feat(build): Start test containers in parallel
  activiti-cloud-starter-audit/pom.xml
Labels: enhancement
